### ISSUE TITLE
Something`s wrong

### ISSUE THREAD

**Issue by JunKuangKuang** [ZaiZheTingDun/hexo-simple-image#1]
when i use this ,it does not work.

Besides,there are nothing to INFO???

![Snipaste_2020-07-06_21-52-17](https://user-images.githubusercontent.com/53326526/86600892-3f58a480-bfd3-11ea-8fe6-e15cedc57f1f.png)

**Comment by JunKuangKuang** [comment]
> when i use this ,it does not work.
> 
> Besides,there are nothing to INFO???
> 
> ![Snipaste_2020-07-06_21-52-17](https://user-images.githubusercontent.com/53326526/86600892-3f58a480-bfd3-11ea-8fe6-e15cedc57f1f.png)

After my research,I found that the filenames cannot be In Chinese.

Can you try to solve it?

**Comment by CPYCalm** [comment]
I also have this problem. There is no problem with the Chinese name of the picture, but there will be a problem if the path is Chinese.

**Comment by CPYCalm** [comment]
I also have this problem. There is no problem with the Chinese name of the picture, but there will be a problem if the path is Chinese.

Examples of errors：
测试/
    测试/
        Test.png
    测试.md

error message:
无法获取/ doc / title / title /

I hope this problem can be fixed.

**Comment by CPYCalm** [comment]
I also have this problem. There is no problem with the Chinese name of the picture, but there will be a problem if the path is Chinese.

Examples of errors：
测试/
----测试/
--------Test.png
----测试.md

error message:
无法获取/ doc / title / title /

I hope this problem can be fixed.

**Comment by onlycalm** [comment]
I also have this problem. There is no problem with the Chinese name of the picture, but there will be a problem if the path is Chinese.

Examples of errors：
测试/
----测试/
--------Test.png
----测试.md

I hope this problem can be fixed.

**Comment by ZaiZheTingDun** [comment]
Does the issue still exist?

![image](https://user-images.githubusercontent.com/27152144/114379734-bacb3000-9bbb-11eb-85ee-1e059ea36826.png)
